name: Dev Install Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  Dev-Install-Test:
    name: Dev Install & Test on Node ${{ matrix.node }} [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # gh macos runnners does not come with docker, could not get it installed
        # see: https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981/3
        # windows runner does not suppport linux containers
        # see:
        os: [ubuntu-latest] #, windows-latest] #,macos-latest]
        node: [18, 20, 21]
    env:
         CYPRESS_RESPONSE_TIMEOUT: 200000
         CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
         CYPRESS_RETRIES: 2
    steps:
      # - name: Install Docker (Macos)
      #   if: ${{ matrix.os == 'macos-latest'}}
      #   run: |
      #     brew install docker-machine docker
      #     docker-machine create default
      #     docker-machine env default
      #     eval "$(docker-machine env default)"
      #     docker ps

      - name: Checkout ab-cli
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install npm packages
        run: npm i

      - name: Initialize docker swarm
        run: docker swarm init 

      - name: Install AppBuilder
        run: node index.js install ab-test --stack=ab-test --develop --port=80 --tag=latest --dbExpose=true --dbPort=8888 --dbPassword=root --authType=login --relayEnabled=false --siteURL=http://localhost:80 --tenant.username=admin --tenant.password=admin --tenant.email=admin@email.com --tenant.url=http://localhost:80

      # Give some time for the stack to come down fully
      - run: sleep 15

      - name: Launch Main Stack
        run: ./UP.sh -t -q
        working-directory: ./ab-test

      - run: docker service ls

      - name: Wait for AB (Main Stack)
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:80
          timeout: 300000

      - run: docker service ls
      
      - name: Run Cypress Tests (Main Stack)
        run: npm run test:e2e:ab-runtime -- --browser chrome
        working-directory: ./ab-test

      - name: Take Down Main Stack
        run: ./Down.sh
        working-directory: ./ab-test

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ABServices.log
          path: ./ab-test/logs/ABServices.log

      # - name: Take Down Test Stack
        # run: node ../index.js test down ab
  podman-install-test:
    name: Podman Install
    runs-on: ubuntu-latest
    env:
         CYPRESS_RESPONSE_TIMEOUT: 200000
         CYPRESS_DEFAULT_COMMAND_TIMEOUT: 30000
         CYPRESS_RETRIES: 2
    steps:
      - run: sudo apt-get update & sudo apt-get -y install podman & systemctl --user enable --now podman.socket
      # connect Docker CLI to Podman’s socket
      - run: export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock


      - run: podman version
      - run: podman compose --help

      - name: Checkout ab-cli
        uses: actions/checkout@v4

      - name: Install npm packages
        run: npm i

      - name: Install AppBuilder
        run: node index.js install ab-test --stack=ab-test --port=80 --tag=latest --dbExpose=true --dbPort=8888 --dbPassword=root --authType=login --relayEnabled=false --siteURL=http://localhost:80 --tenant.username=admin --tenant.password=admin --tenant.email=admin@email.com --tenant.url=http://localhost:80 --platform=podman

      # Give some time for the stack to come down fully
      - run: sleep 15
      - name: Launch Main Stack
        run: ./UP.sh -t -q
        working-directory: ./ab-test

      - name: Wait for AB (Main Stack)
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:80
          timeout: 300000

      - name: Run Cypress Tests (Main Stack)
        run: npm run test:e2e:ab-runtime -- --browser chrome
        working-directory: ./ab-test

      - name: Take Down Main Stack
        run: ./Down.sh
        working-directory: ./ab-test

